// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uslzknsgiqjzayyrcdok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbHprbnNnaXFqemF5eXJjZG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDE0NzMsImV4cCI6MjA2ODUxNzQ3M30.yMTC0GnxxnHEdAYl5-7hUFClFDTOVgc-0OPRqXL1fkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});